name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      -name: print greeeting
        run: echo "hello world"
      - name: print goodbye
        run:echo "done-bye"
